export interface GameDataItemsCategoriesStatInfusions {
    /** The item id */
    id: number

    /** The item name */
    name: string
}

// prettier-ignore
const GAME_DATA_ITEMS_CATEGORIES_STAT_INFUSIONS: Array<GameDataItemsCategoriesStatInfusions> = [
// -- GENERATE-START --
  { name: 'Healing +9 Agony Infusion', id: 37125 },
  { name: 'Healing +7 Agony Infusion', id: 37123 },
  { name: 'Mighty +7 Agony Infusion', id: 37127 },
  { name: 'Precise +7 Agony Infusion', id: 37128 },
  { name: 'Malign +7 Agony Infusion', id: 37129 },
  { name: 'Malign +9 Agony Infusion', id: 37130 },
  { name: 'Mighty +9 Agony Infusion', id: 37131 },
  { name: 'Precise +9 Agony Infusion', id: 37132 },
  { name: 'Resilient +7 Agony Infusion', id: 37133 },
  { name: 'Vital +7 Agony Infusion', id: 37134 },
  { name: 'Resilient +9 Agony Infusion', id: 37135 },
  { name: 'Vital +9 Agony Infusion', id: 37136 },
  { name: 'Precise Infusion', id: 39335 },
  { name: 'Mighty Infusion', id: 39336 },
  { name: 'Malign Infusion', id: 39337 },
  { name: 'Vital Infusion', id: 39338 },
  { name: 'Resilient Infusion', id: 39339 },
  { name: 'Healing Infusion', id: 39340 },
  { name: 'Healing +5 Agony Infusion', id: 39616 },
  { name: 'Resilient +5 Agony Infusion', id: 39617 },
  { name: 'Vital +5 Agony Infusion', id: 39618 },
  { name: 'Malign +5 Agony Infusion', id: 39619 },
  { name: 'Mighty +5 Agony Infusion', id: 39620 },
  { name: 'Precise +5 Agony Infusion', id: 39621 },
  { name: 'Healing WvW Infusion', id: 43250 },
  { name: 'Resilient WvW Infusion', id: 43251 },
  { name: 'Vital WvW Infusion', id: 43252 },
  { name: 'Malign WvW Infusion', id: 43253 },
  { name: 'Mighty WvW Infusion', id: 43254 },
  { name: 'Precise WvW Infusion', id: 43255 },
  { name: 'Ghostly Infusion', id: 77274 },
  { name: 'Ghostly Infusion', id: 77303 },
  { name: 'Ghostly Infusion', id: 77310 },
  { name: 'Ghostly Infusion', id: 77316 },
  { name: 'Ghostly Infusion', id: 77366 },
  { name: 'Ghostly Infusion', id: 77394 },
  { name: 'Moto\'s Unstable Bauble Infusion: Blue', id: 78012 },
  { name: 'Moto\'s Unstable Bauble Infusion: Red', id: 78016 },
  { name: 'Moto\'s Unstable Bauble Infusion: Red', id: 78028 },
  { name: 'Moto\'s Unstable Bauble Infusion: Red', id: 78030 },
  { name: 'Moto\'s Unstable Bauble Infusion: Red', id: 78031 },
  { name: 'Moto\'s Unstable Bauble Infusion: Blue', id: 78052 },
  { name: 'Moto\'s Unstable Bauble Infusion: Blue', id: 78054 },
  { name: 'Moto\'s Unstable Bauble Infusion: Red', id: 78057 },
  { name: 'Moto\'s Unstable Bauble Infusion: Blue', id: 78079 },
  { name: 'Moto\'s Unstable Bauble Infusion: Blue', id: 78086 },
  { name: 'Moto\'s Unstable Bauble Infusion: Blue', id: 78090 },
  { name: 'Moto\'s Unstable Bauble Infusion: Red', id: 78097 },
  { name: 'Phospholuminescent Infusion', id: 79665 },
  { name: 'Phospholuminescent Infusion', id: 79674 },
  { name: 'Phospholuminescent Infusion', id: 79639 },
  { name: 'Phospholuminescent Infusion', id: 79653 },
  { name: 'Phospholuminescent Infusion', id: 79661 },
  { name: 'Phospholuminescent Infusion', id: 79669 },
  { name: 'Winter\'s Heart Infusion', id: 79959 },
  { name: 'Winter\'s Heart Infusion', id: 79957 },
  { name: 'Winter\'s Heart Infusion', id: 79978 },
  { name: 'Winter\'s Heart Infusion', id: 79994 },
  { name: 'Winter\'s Heart Infusion', id: 79943 },
  { name: 'Winter\'s Heart Infusion', id: 80063 },
  { name: 'Polyluminescent Undulating Infusion (Teal)', id: 81653 },
  { name: 'Queen Bee Infusion', id: 81663 },
  { name: 'Polyluminescent Undulating Infusion (Green)', id: 81678 },
  { name: 'Polyluminescent Undulating Infusion (Teal)', id: 81777 },
  { name: 'Celestial Infusion (Red)', id: 81783 },
  { name: 'Polyluminescent Undulating Infusion (Orange)', id: 81809 },
  { name: 'Polyluminescent Undulating Infusion (Black)', id: 81810 },
  { name: 'Celestial Infusion (Red)', id: 81814 },
  { name: 'Chak Infusion', id: 81825 },
  { name: 'Polyluminescent Undulating Infusion (Orange)', id: 81847 },
  { name: 'Polyluminescent Undulating Infusion (Orange)', id: 81864 },
  { name: 'Polyluminescent Undulating Infusion (Black)', id: 81877 },
  { name: 'Polyluminescent Undulating Infusion (Orange)', id: 81930 },
  { name: 'Polyluminescent Undulating Infusion (Black)', id: 82013 },
  { name: 'Polyluminescent Undulating Infusion (Green)', id: 82055 },
  { name: 'Polyluminescent Undulating Infusion (Green)', id: 81612 },
  { name: 'Chak Infusion', id: 81616 },
  { name: 'Polyluminescent Undulating Infusion (Black)', id: 81624 },
  { name: 'Queen Bee Infusion', id: 81638 },
  { name: 'Polyluminescent Undulating Infusion (Teal)', id: 81641 },
  { name: 'Queen Bee Infusion', id: 81679 },
  { name: 'Polyluminescent Undulating Infusion (Teal)', id: 81655 },
  { name: 'Queen Bee Infusion', id: 81701 },
  { name: 'Polyluminescent Undulating Infusion (Black)', id: 81709 },
  { name: 'Polyluminescent Undulating Infusion (Green)', id: 81727 },
  { name: 'Celestial Infusion (Blue)', id: 81761 },
  { name: 'Celestial Infusion (Blue)', id: 81779 },
  { name: 'Chak Infusion', id: 81807 },
  { name: 'Queen Bee Infusion', id: 81818 },
  { name: 'Celestial Infusion (Blue)', id: 81811 },
  { name: 'Polyluminescent Undulating Infusion (Teal)', id: 81858 },
  { name: 'Polyluminescent Undulating Infusion (Orange)', id: 81881 },
  { name: 'Queen Bee Infusion', id: 81897 },
  { name: 'Polyluminescent Undulating Infusion (Orange)', id: 81911 },
  { name: 'Celestial Infusion (Blue)', id: 81919 },
  { name: 'Celestial Infusion (Red)', id: 81927 },
  { name: 'Polyluminescent Undulating Infusion (Green)', id: 81948 },
  { name: 'Polyluminescent Undulating Infusion (Teal)', id: 81959 },
  { name: 'Polyluminescent Undulating Infusion (Green)', id: 81988 },
  { name: 'Celestial Infusion (Blue)', id: 81991 },
  { name: 'Polyluminescent Undulating Infusion (Black)', id: 82039 },
  { name: 'Chak Infusion', id: 82044 },
  { name: 'Liquid Aurillium Infusion', id: 81715 },
  { name: 'Liquid Aurillium Infusion', id: 82006 },
  { name: 'Celestial Infusion (Blue)', id: 81878 },
  { name: 'Chak Infusion', id: 81677 },
  { name: 'Chak Infusion', id: 81840 },
  { name: 'Liquid Aurillium Infusion', id: 81875 },
  { name: 'Celestial Infusion (Red)', id: 81792 },
  { name: 'Liquid Aurillium Infusion', id: 81889 },
  { name: 'Liquid Aurillium Infusion', id: 81918 },
  { name: 'Liquid Aurillium Infusion', id: 81975 },
  { name: 'Celestial Infusion (Red)', id: 82062 },
  { name: 'Celestial Infusion (Red)', id: 82070 },
  { name: 'Festive Confetti Infusion', id: 84970 },
  { name: 'Festive Confetti Infusion', id: 84871 },
  { name: 'Festive Confetti Infusion', id: 84882 },
  { name: 'Ghostly Infusion', id: 85644 },
  { name: 'Celestial Infusion (Red)', id: 85646 },
  { name: 'Polyluminescent Undulating Infusion (Orange)', id: 85694 },
  { name: 'Winter\'s Heart Infusion', id: 85718 },
  { name: 'Celestial Infusion (Red)', id: 85833 },
  { name: 'Phospholuminescent Infusion', id: 85863 },
  { name: 'Mystical +7 Agony Infusion', id: 85881 },
  { name: 'Phospholuminescent Infusion', id: 85885 },
  { name: 'Ghostly Infusion', id: 85945 },
  { name: 'Spiteful +5 Agony Infusion', id: 85971 },
  { name: 'Queen Bee Infusion', id: 86055 },
  { name: 'Spiteful +9 Agony Infusion', id: 86113 },
  { name: 'Spiteful +7 Agony Infusion', id: 86150 },
  { name: 'Mystical +9 Agony Infusion', id: 86180 },
  { name: 'Polyluminescent Undulating Infusion (Black)', id: 86248 },
  { name: 'Chak Infusion', id: 86251 },
  { name: 'Liquid Aurillium Infusion', id: 86275 },
  { name: 'Mystical +5 Agony Infusion', id: 86338 },
  { name: 'Winter\'s Heart Infusion', id: 85734 },
  { name: 'Polyluminescent Undulating Infusion (Black)', id: 85974 },
  { name: 'Polyluminescent Undulating Infusion (Green)', id: 86183 },
  { name: 'Celestial Infusion (Blue)', id: 85989 },
  { name: 'Polyluminescent Undulating Infusion (Orange)', id: 86310 },
  { name: 'Polyluminescent Undulating Infusion (Teal)', id: 86312 },
  { name: 'Celestial Infusion (Blue)', id: 86347 },
  { name: 'Polyluminescent Undulating Infusion (Teal)', id: 86068 },
  { name: 'Liquid Aurillium Infusion', id: 86291 },
  { name: 'Queen Bee Infusion', id: 86303 },
  { name: 'Snow Diamond Infusion', id: 86401 },
  { name: 'Snow Diamond Infusion', id: 86405 },
  { name: 'Snow Diamond Infusion', id: 86407 },
  { name: 'Moto\'s Unstable Bauble Infusion: Red', id: 86446 },
  { name: 'Moto\'s Unstable Bauble Infusion: Red', id: 86453 },
  { name: 'Moto\'s Unstable Bauble Infusion: Blue', id: 86571 },
  { name: 'Moto\'s Unstable Bauble Infusion: Blue', id: 86552 },
  { name: 'Snow Diamond Infusion', id: 86537 },
  { name: 'Snow Diamond Infusion', id: 86665 },
  { name: 'Snow Diamond Infusion', id: 86666 },
  { name: 'Chak Infusion', id: 85668 },
  { name: 'Snow Diamond Infusion', id: 86597 },
  { name: 'Snow Diamond Infusion', id: 86704 },
  { name: 'Polyluminescent Undulating Infusion (Green)', id: 85682 },
  { name: 'Festive Confetti Infusion', id: 85900 },
  { name: 'Concentration WvW Infusion', id: 86986 },
  { name: 'Expertise WvW Infusion', id: 87218 },
  { name: 'Festive Confetti Infusion', id: 84937 },
  { name: 'Festive Confetti Infusion', id: 84959 },
  { name: 'Festive Confetti Infusion', id: 85996 },
  { name: 'Crystal Infusion of Power', id: 88771 },
  { name: 'Crystal Infusion of Boon Duration', id: 88770 },
  { name: 'Polysaturating Reverberating Infusion (Gray)', id: 89007 },
  { name: 'Polysaturating Reverberating Infusion (Gray)', id: 89020 },
  { name: 'Polysaturating Reverberating Infusion (Purple)', id: 89063 },
  { name: 'Polysaturating Reverberating Infusion (Purple)', id: 89070 },
  { name: 'Polysaturating Reverberating Infusion (Red)', id: 89059 },
  { name: 'Ember Infusion', id: 89065 },
  { name: 'Polysaturating Reverberating Infusion (Red)', id: 89071 },
  { name: 'Polysaturating Reverberating Infusion (Gray)', id: 89012 },
  { name: 'Polysaturating Reverberating Infusion (Gray)', id: 89016 },
  { name: 'Polysaturating Reverberating Infusion (Red)', id: 89028 },
  { name: 'Polysaturating Reverberating Infusion (Purple)', id: 89049 },
  { name: 'Ember Infusion', id: 89046 },
  { name: 'Polysaturating Reverberating Infusion (Gray)', id: 89054 },
  { name: 'Polysaturating Reverberating Infusion (Gray)', id: 89078 },
  { name: 'Polysaturating Reverberating Infusion (Gray)', id: 89074 },
  { name: 'Polysaturating Reverberating Infusion (Purple)', id: 89017 },
  { name: 'Polysaturating Reverberating Infusion (Gray)', id: 89013 },
  { name: 'Polysaturating Reverberating Infusion (Red)', id: 89034 },
  { name: 'Polysaturating Reverberating Infusion (Red)', id: 89026 },
  { name: 'Polysaturating Reverberating Infusion (Purple)', id: 89039 },
  { name: 'Ember Infusion', id: 89060 },
  { name: 'Polysaturating Reverberating Infusion (Red)', id: 89032 },
  { name: 'Polysaturating Reverberating Infusion (Purple)', id: 89037 },
  { name: 'Polysaturating Reverberating Infusion (Purple)', id: 89005 },
  { name: 'Polysaturating Reverberating Infusion (Red)', id: 89052 },
  { name: 'Polysaturating Reverberating Infusion (Red)', id: 89075 },
  { name: 'Ember Infusion', id: 89038 },
  { name: 'Polysaturating Reverberating Infusion (Purple)', id: 89042 },
  { name: 'Crystal Infusion of Condition Damage', id: 88732 },
  { name: 'Ember Infusion', id: 89010 },
  { name: 'Ember Infusion', id: 89040 },
  { name: 'Ember Infusion', id: 89021 },
  { name: 'Ember Infusion', id: 89015 },
  { name: 'Toy-Shell Infusion', id: 89382 },
  { name: 'Toy-Shell Infusion', id: 89391 },
  { name: 'Toy-Shell Infusion', id: 89401 },
  { name: 'Toy-Shell Infusion', id: 89411 },
  { name: 'Toy-Shell Infusion', id: 89426 },
  { name: 'Toy-Shell Infusion', id: 89415 },
  { name: 'Toy-Shell Infusion', id: 89413 },
  { name: 'Toy-Shell Infusion', id: 89427 },
  { name: 'Mystic Infusion', id: 90966 },
  { name: 'Mystic Infusion', id: 91111 },
  { name: 'Mystic Infusion', id: 91050 },
  { name: 'Mystic Infusion', id: 90982 },
  { name: 'Mystic Infusion', id: 91086 },
  { name: 'Mystic Infusion', id: 91099 },
  { name: 'Mystic Infusion', id: 91054 },
  { name: 'Mystic Infusion', id: 90977 },
  { name: 'Peerless Infusion', id: 91140 },
  { name: 'Peerless Infusion', id: 91152 },
  { name: 'Peerless Infusion', id: 91154 },
  { name: 'Peerless Infusion', id: 91180 },
  { name: 'Peerless Infusion', id: 91202 },
  { name: 'Peerless Infusion', id: 91210 },
  { name: 'Peerless Infusion', id: 91221 },
  { name: 'Peerless Infusion', id: 91236 },
  { name: 'Crystal Infusion of Precision', id: 88871 },
  { name: 'Crystal Infusion of Condition Duration', id: 88876 },
  { name: 'Crystal Infusion of Vitality', id: 88522 },
  { name: 'Festive Confetti Infusion', id: 85033 },
  { name: 'Crystal Infusion of Healing', id: 88603 },
  { name: 'Heart of the Khan-Ur', id: 92023 },
  { name: 'Heart of the Khan-Ur', id: 91930 },
  { name: 'Heart of the Khan-Ur', id: 91897 },
  { name: 'Heart of the Khan-Ur', id: 91923 },
  { name: 'Heart of the Khan-Ur', id: 91996 },
  { name: 'Heart of the Khan-Ur', id: 92018 },
  { name: 'Heart of the Khan-Ur', id: 92073 },
  { name: 'Heart of the Khan-Ur', id: 92075 },
  { name: 'Frost Legion Infusion', id: 93829 },
  { name: 'Frost Legion Infusion', id: 93906 },
  { name: 'Frost Legion Infusion', id: 93758 },
  { name: 'Frost Legion Infusion', id: 93720 },
  { name: 'Frost Legion Infusion', id: 93858 },
  { name: 'Frost Legion Infusion', id: 93773 },
  { name: 'Frost Legion Infusion', id: 93775 },
  { name: 'Abyssal Infusion', id: 94010 },
  { name: 'Abyssal Infusion', id: 94024 },
  { name: 'Abyssal Infusion', id: 94028 },
  { name: 'Abyssal Infusion', id: 94039 },
  { name: 'Abyssal Infusion', id: 94079 },
  { name: 'Abyssal Infusion', id: 94078 },
  { name: 'Abyssal Infusion', id: 94090 },
  { name: 'Abyssal Infusion', id: 94091 },
  { name: 'Frost Legion Infusion', id: 93920 },
  { name: 'Deldrimor Stoneskin Infusion', id: 94609 },
  { name: 'Deldrimor Stoneskin Infusion', id: 94584 },
  { name: 'Deldrimor Stoneskin Infusion', id: 94481 },
  { name: 'Deldrimor Stoneskin Infusion', id: 94543 },
  { name: 'Deldrimor Stoneskin Infusion', id: 94572 },
  { name: 'Deldrimor Stoneskin Infusion', id: 94484 },
  { name: 'Deldrimor Stoneskin Infusion', id: 94583 },
  { name: 'Deldrimor Stoneskin Infusion', id: 94487 },
  { name: 'Jormag Left Eye Infusion', id: 94949 },
  { name: 'Primordus Right Eye Infusion', id: 94941 },
  { name: 'Jormag Left Eye Infusion', id: 94980 },
  { name: 'Primordus Right Eye Infusion', id: 94955 },
  { name: 'Primordus Left Eye Infusion', id: 94978 },
  { name: 'Primordus Left Eye Infusion', id: 94964 },
  { name: 'Jormag Right Eye Infusion', id: 94979 },
  { name: 'Jormag Left Eye Infusion', id: 94929 },
  { name: 'Jormag Right Eye Infusion', id: 94958 },
  { name: 'Jormag Right Eye Infusion', id: 94946 },
  { name: 'Jormag Left Eye Infusion', id: 94969 },
  { name: 'Jormag Right Eye Infusion', id: 94934 },
  { name: 'Jormag Left Eye Infusion', id: 94954 },
  { name: 'Jormag Left Eye Infusion', id: 94944 },
  { name: 'Primordus Right Eye Infusion', id: 94928 },
  { name: 'Primordus Left Eye Infusion', id: 94965 },
  { name: 'Jormag Right Eye Infusion', id: 94938 },
  { name: 'Primordus Left Eye Infusion', id: 94935 },
  { name: 'Jormag Right Eye Infusion', id: 94948 },
  { name: 'Primordus Right Eye Infusion', id: 94971 },
  { name: 'Primordus Right Eye Infusion', id: 94930 },
  { name: 'Primordus Left Eye Infusion', id: 94951 },
  { name: 'Jormag Right Eye Infusion', id: 94972 },
  { name: 'Primordus Left Eye Infusion', id: 94943 },
  { name: 'Primordus Left Eye Infusion', id: 94970 },
  { name: 'Jormag Left Eye Infusion', id: 94937 },
  { name: 'Primordus Right Eye Infusion', id: 94977 },
  { name: 'Crystal Infusion of Toughness', id: 88683 },
  { name: 'Primordus Right Eye Infusion', id: 94952 },
  { name: 'Primordus Right Eye Infusion', id: 94939 },
  { name: 'Primordus Left Eye Infusion', id: 94957 },
  { name: 'Jormag Left Eye Infusion', id: 94963 },
  { name: 'Jormag Right Eye Infusion', id: 94962 },
  { name: 'Echo of the Dragonvoid', id: 97993 },
  { name: 'Echo of the Dragonvoid', id: 98028 },
  { name: 'Echo of the Dragonvoid', id: 98023 },
  { name: 'Echo of the Dragonvoid', id: 98004 },
  { name: 'Echo of the Dragonvoid', id: 98043 },
  { name: 'Echo of the Dragonvoid', id: 98022 },
  { name: 'Imperial Everbloom', id: 98163 },
  { name: 'Imperial Everbloom', id: 98153 },
  { name: 'Imperial Everbloom', id: 98088 },
  { name: 'Imperial Everbloom', id: 98105 },
  { name: 'Imperial Everbloom', id: 98083 },
  { name: 'Imperial Everbloom', id: 98145 },
  { name: 'Imperial Everbloom', id: 98131 },
  { name: 'Imperial Everbloom', id: 98119 },
  { name: 'Echo of the Dragonvoid', id: 98066 },
  { name: 'Echo of the Dragonvoid', id: 98020 },
  { name: 'Clockwork Infusion', id: 99240 },
  { name: 'Clockwork Infusion', id: 99248 },
  { name: 'Clockwork Infusion', id: 99195 },
  { name: 'Clockwork Infusion', id: 99237 },
  { name: 'Clockwork Infusion', id: 99209 },
  { name: 'Clockwork Infusion', id: 99244 },
  { name: 'Clockwork Infusion', id: 99213 },
  { name: 'Clockwork Infusion', id: 99206 },
  { name: 'Mistwalker Infusion', id: 99784 },
  { name: 'Mistwalker Infusion', id: 99789 },
  { name: 'Mistwalker Infusion', id: 99790 },
  { name: 'Mistwalker Infusion', id: 99809 },
  { name: 'Mistwalker Infusion', id: 99824 },
  { name: 'Mistwalker Infusion', id: 99839 },
  { name: 'Mistwalker Infusion', id: 99848 },
  { name: 'Mistwalker Infusion', id: 99850 },
  { name: 'Mote of Darkness', id: 99880 },
  { name: 'Mote of Darkness', id: 99882 },
  { name: 'Mote of Darkness', id: 99878 },
  { name: 'Mote of Darkness', id: 99881 },
  { name: 'Mote of Darkness', id: 99887 },
  { name: 'Mote of Darkness', id: 99898 },
  { name: 'Mote of Darkness', id: 99894 },
  { name: 'Mote of Darkness', id: 99869 },
  { name: 'Silent Symphony', id: 99921 },
  { name: 'Silent Symphony', id: 99940 },
  { name: 'Silent Symphony', id: 99948 },
  { name: 'Silent Symphony', id: 99939 },
  { name: 'Silent Symphony', id: 99932 },
  { name: 'Silent Symphony', id: 99929 },
  { name: 'Silent Symphony', id: 99914 },
  { name: 'Silent Symphony', id: 99946 },
  { name: 'Arcane Flow Infusion', id: 101199 },
  { name: 'Arcane Flow Infusion', id: 101237 },
  { name: 'Arcane Flow Infusion', id: 101234 },
  { name: 'Jotun Infusion', id: 101276 },
  { name: 'Arcane Flow Infusion', id: 101279 },
  { name: 'Arcane Flow Infusion', id: 101261 },
  { name: 'Arcane Flow Infusion', id: 101278 },
  { name: 'Arcane Flow Infusion', id: 101223 },
  { name: 'Arcane Flow Infusion', id: 101263 },
  { name: 'Jotun Infusion', id: 101146 },
  { name: 'Jotun Infusion', id: 101226 },
  { name: 'Jotun Infusion', id: 101124 },
  { name: 'Jotun Infusion', id: 101259 },
  { name: 'Jotun Infusion', id: 101262 },
  { name: 'Jotun Infusion', id: 101171 },
  { name: 'Jotun Infusion', id: 101169 },
  { name: 'Possession Infusion', id: 100008 },
  { name: 'Possession Infusion', id: 100513 },
  { name: 'Possession Infusion', id: 100806 },
  { name: 'Possession Infusion', id: 100302 },
  { name: 'Possession Infusion', id: 100914 },
  { name: 'Possession Infusion', id: 100407 },
  // -- GENERATE-END --
]

export default GAME_DATA_ITEMS_CATEGORIES_STAT_INFUSIONS