export interface GameDataItemsCategoriesCosmeticAura {
  /** The grouping key for the aura */
  aura_key: string

  /** The item id */
  id: number

  /** The item name */
  name: string
}

// prettier-ignore
const GAME_DATA_ITEMS_CATEGORIES_COSMETIC_AURAS: Array<GameDataItemsCategoriesCosmeticAura> = [
  // -- GENERATE-START --
  { aura_key: 'kodasWarmthEnrichment', id: 79926, name: 'Koda\'s Warmth Enrichment' },

  { aura_key: 'frostLegionInfusion', id: 93720, name: 'Frost Legion Infusion' },
  { aura_key: 'frostLegionInfusion', id: 93758, name: 'Frost Legion Infusion' },
  { aura_key: 'frostLegionInfusion', id: 93773, name: 'Frost Legion Infusion' },
  { aura_key: 'frostLegionInfusion', id: 93775, name: 'Frost Legion Infusion' },
  { aura_key: 'frostLegionInfusion', id: 93829, name: 'Frost Legion Infusion' },
  { aura_key: 'frostLegionInfusion', id: 93858, name: 'Frost Legion Infusion' },
  { aura_key: 'frostLegionInfusion', id: 93906, name: 'Frost Legion Infusion' },
  { aura_key: 'frostLegionInfusion', id: 93920, name: 'Frost Legion Infusion' },

  { aura_key: 'ottersBlessingEnrichment', id: 93798, name: 'Otter\'s Blessing Enrichment' },

  { aura_key: 'celebratoryBirthdayEnrichment', id: 93953, name: 'Celebratory Birthday Enrichment' },

  { aura_key: 'jormagEyeInfusions', id: 94929, name: 'Jormag Left Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94934, name: 'Jormag Right Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94937, name: 'Jormag Left Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94938, name: 'Jormag Right Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94944, name: 'Jormag Left Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94946, name: 'Jormag Right Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94948, name: 'Jormag Right Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94949, name: 'Jormag Left Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94954, name: 'Jormag Left Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94958, name: 'Jormag Right Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94962, name: 'Jormag Right Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94963, name: 'Jormag Left Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94969, name: 'Jormag Left Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94972, name: 'Jormag Right Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94979, name: 'Jormag Right Eye Infusion' },
  { aura_key: 'jormagEyeInfusions', id: 94980, name: 'Jormag Left Eye Infusion' },

  { aura_key: 'primordusEyeInfusions', id: 94928, name: 'Primordus Right Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94930, name: 'Primordus Right Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94935, name: 'Primordus Left Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94939, name: 'Primordus Right Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94941, name: 'Primordus Right Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94943, name: 'Primordus Left Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94951, name: 'Primordus Left Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94952, name: 'Primordus Right Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94955, name: 'Primordus Right Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94957, name: 'Primordus Left Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94964, name: 'Primordus Left Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94965, name: 'Primordus Left Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94970, name: 'Primordus Left Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94971, name: 'Primordus Right Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94977, name: 'Primordus Right Eye Infusion' },
  { aura_key: 'primordusEyeInfusions', id: 94978, name: 'Primordus Left Eye Infusion' },

  { aura_key: 'wurmsBlessingEnrichment', id: 101126, name: 'Wurm\'s Karmic Blessing Enrichment' },
  { aura_key: 'wurmsBlessingEnrichment', id: 101187, name: 'Wurm\'s WXP Blessing Enrichment' },
  { aura_key: 'wurmsBlessingEnrichment', id: 101193, name: 'Wurm\'s WvW Reward Track Blessing Enrichment' },
  { aura_key: 'wurmsBlessingEnrichment', id: 101250, name: 'Wurm\'s Experienced Blessing Enrichment' },
  { aura_key: 'wurmsBlessingEnrichment', id: 101272, name: 'Wurm\'s Gilded Blessing Enrichment' },
  { aura_key: 'wurmsBlessingEnrichment', id: 101302, name: 'Wurm\'s Magical Blessing Enrichment' },

  { aura_key: 'preservedQueenBees', id: 68440, name: 'Preserved Queen Bee' },
  { aura_key: 'preservedQueenBees', id: 77594, name: 'Preserved Queen Bee' },
  { aura_key: 'preservedQueenBees', id: 81638, name: 'Queen Bee Infusion' },
  { aura_key: 'preservedQueenBees', id: 81663, name: 'Queen Bee Infusion' },
  { aura_key: 'preservedQueenBees', id: 81679, name: 'Queen Bee Infusion' },
  { aura_key: 'preservedQueenBees', id: 81701, name: 'Queen Bee Infusion' },
  { aura_key: 'preservedQueenBees', id: 81818, name: 'Queen Bee Infusion' },
  { aura_key: 'preservedQueenBees', id: 81897, name: 'Queen Bee Infusion' },
  { aura_key: 'preservedQueenBees', id: 86055, name: 'Queen Bee Infusion' },
  { aura_key: 'preservedQueenBees', id: 86303, name: 'Queen Bee Infusion' },

  { aura_key: 'liquidAurillium', id: 76063, name: 'Vial of Liquid Aurillium' },
  { aura_key: 'liquidAurillium', id: 81715, name: 'Liquid Aurillium Infusion' },
  { aura_key: 'liquidAurillium', id: 81875, name: 'Liquid Aurillium Infusion' },
  { aura_key: 'liquidAurillium', id: 81889, name: 'Liquid Aurillium Infusion' },
  { aura_key: 'liquidAurillium', id: 81918, name: 'Liquid Aurillium Infusion' },
  { aura_key: 'liquidAurillium', id: 81975, name: 'Liquid Aurillium Infusion' },
  { aura_key: 'liquidAurillium', id: 82006, name: 'Liquid Aurillium Infusion' },
  { aura_key: 'liquidAurillium', id: 86275, name: 'Liquid Aurillium Infusion' },
  { aura_key: 'liquidAurillium', id: 86291, name: 'Liquid Aurillium Infusion' },

  { aura_key: 'chakEggSacks', id: 72021, name: 'Chak Egg Sac' },
  { aura_key: 'chakEggSacks', id: 81616, name: 'Chak Infusion' },
  { aura_key: 'chakEggSacks', id: 81677, name: 'Chak Infusion' },
  { aura_key: 'chakEggSacks', id: 81807, name: 'Chak Infusion' },
  { aura_key: 'chakEggSacks', id: 81825, name: 'Chak Infusion' },
  { aura_key: 'chakEggSacks', id: 81840, name: 'Chak Infusion' },
  { aura_key: 'chakEggSacks', id: 82044, name: 'Chak Infusion' },
  { aura_key: 'chakEggSacks', id: 85668, name: 'Chak Infusion' },
  { aura_key: 'chakEggSacks', id: 86251, name: 'Chak Infusion' },

  { aura_key: 'festiveConfettiInfusions', id: 84871, name: 'Festive Confetti Infusion' },
  { aura_key: 'festiveConfettiInfusions', id: 84882, name: 'Festive Confetti Infusion' },
  { aura_key: 'festiveConfettiInfusions', id: 84937, name: 'Festive Confetti Infusion' },
  { aura_key: 'festiveConfettiInfusions', id: 84959, name: 'Festive Confetti Infusion' },
  { aura_key: 'festiveConfettiInfusions', id: 84970, name: 'Festive Confetti Infusion' },
  { aura_key: 'festiveConfettiInfusions', id: 85033, name: 'Festive Confetti Infusion' },
  { aura_key: 'festiveConfettiInfusions', id: 85900, name: 'Festive Confetti Infusion' },
  { aura_key: 'festiveConfettiInfusions', id: 85996, name: 'Festive Confetti Infusion' },

  { aura_key: 'crystalInfusions', id: 88522, name: 'Crystal Infusion of Vitality' },
  { aura_key: 'crystalInfusions', id: 88603, name: 'Crystal Infusion of Healing' },
  { aura_key: 'crystalInfusions', id: 88683, name: 'Crystal Infusion of Toughness' },
  { aura_key: 'crystalInfusions', id: 88732, name: 'Crystal Infusion of Condition Damage' },
  { aura_key: 'crystalInfusions', id: 88770, name: 'Crystal Infusion of Boon Duration' },
  { aura_key: 'crystalInfusions', id: 88771, name: 'Crystal Infusion of Power' },
  { aura_key: 'crystalInfusions', id: 88871, name: 'Crystal Infusion of Precision' },
  { aura_key: 'crystalInfusions', id: 88876, name: 'Crystal Infusion of Condition Duration' },

  { aura_key: 'heartOfTheKhanUr', id: 91897, name: 'Heart of the Khan-Ur' },
  { aura_key: 'heartOfTheKhanUr', id: 91923, name: 'Heart of the Khan-Ur' },
  { aura_key: 'heartOfTheKhanUr', id: 91930, name: 'Heart of the Khan-Ur' },
  { aura_key: 'heartOfTheKhanUr', id: 91996, name: 'Heart of the Khan-Ur' },
  { aura_key: 'heartOfTheKhanUr', id: 92018, name: 'Heart of the Khan-Ur' },
  { aura_key: 'heartOfTheKhanUr', id: 92023, name: 'Heart of the Khan-Ur' },
  { aura_key: 'heartOfTheKhanUr', id: 92073, name: 'Heart of the Khan-Ur' },
  { aura_key: 'heartOfTheKhanUr', id: 92075, name: 'Heart of the Khan-Ur' },

  { aura_key: 'deldrimorStoneskinInfusions', id: 94481, name: 'Deldrimor Stoneskin Infusion' },
  { aura_key: 'deldrimorStoneskinInfusions', id: 94484, name: 'Deldrimor Stoneskin Infusion' },
  { aura_key: 'deldrimorStoneskinInfusions', id: 94487, name: 'Deldrimor Stoneskin Infusion' },
  { aura_key: 'deldrimorStoneskinInfusions', id: 94543, name: 'Deldrimor Stoneskin Infusion' },
  { aura_key: 'deldrimorStoneskinInfusions', id: 94572, name: 'Deldrimor Stoneskin Infusion' },
  { aura_key: 'deldrimorStoneskinInfusions', id: 94583, name: 'Deldrimor Stoneskin Infusion' },
  { aura_key: 'deldrimorStoneskinInfusions', id: 94584, name: 'Deldrimor Stoneskin Infusion' },
  { aura_key: 'deldrimorStoneskinInfusions', id: 94609, name: 'Deldrimor Stoneskin Infusion' },

  { aura_key: 'echoOfTheDragonvoid', id: 97993, name: 'Echo of the Dragonvoid' },
  { aura_key: 'echoOfTheDragonvoid', id: 98004, name: 'Echo of the Dragonvoid' },
  { aura_key: 'echoOfTheDragonvoid', id: 98020, name: 'Echo of the Dragonvoid' },
  { aura_key: 'echoOfTheDragonvoid', id: 98022, name: 'Echo of the Dragonvoid' },
  { aura_key: 'echoOfTheDragonvoid', id: 98023, name: 'Echo of the Dragonvoid' },
  { aura_key: 'echoOfTheDragonvoid', id: 98028, name: 'Echo of the Dragonvoid' },
  { aura_key: 'echoOfTheDragonvoid', id: 98043, name: 'Echo of the Dragonvoid' },
  { aura_key: 'echoOfTheDragonvoid', id: 98066, name: 'Echo of the Dragonvoid' },

  { aura_key: 'celestialInfusionBlue', id: 81761, name: 'Celestial Infusion (Blue)' },
  { aura_key: 'celestialInfusionBlue', id: 81779, name: 'Celestial Infusion (Blue)' },
  { aura_key: 'celestialInfusionBlue', id: 81811, name: 'Celestial Infusion (Blue)' },
  { aura_key: 'celestialInfusionBlue', id: 81878, name: 'Celestial Infusion (Blue)' },
  { aura_key: 'celestialInfusionBlue', id: 81919, name: 'Celestial Infusion (Blue)' },
  { aura_key: 'celestialInfusionBlue', id: 81991, name: 'Celestial Infusion (Blue)' },
  { aura_key: 'celestialInfusionBlue', id: 85989, name: 'Celestial Infusion (Blue)' },
  { aura_key: 'celestialInfusionBlue', id: 86347, name: 'Celestial Infusion (Blue)' },

  { aura_key: 'celestialInfusionRed', id: 81783, name: 'Celestial Infusion (Red)' },
  { aura_key: 'celestialInfusionRed', id: 81792, name: 'Celestial Infusion (Red)' },
  { aura_key: 'celestialInfusionRed', id: 81814, name: 'Celestial Infusion (Red)' },
  { aura_key: 'celestialInfusionRed', id: 81927, name: 'Celestial Infusion (Red)' },
  { aura_key: 'celestialInfusionRed', id: 82062, name: 'Celestial Infusion (Red)' },
  { aura_key: 'celestialInfusionRed', id: 82070, name: 'Celestial Infusion (Red)' },
  { aura_key: 'celestialInfusionRed', id: 85646, name: 'Celestial Infusion (Red)' },
  { aura_key: 'celestialInfusionRed', id: 85833, name: 'Celestial Infusion (Red)' },

  { aura_key: 'abyssalInfusion', id: 94010, name: 'Abyssal Infusion' },
  { aura_key: 'abyssalInfusion', id: 94024, name: 'Abyssal Infusion' },
  { aura_key: 'abyssalInfusion', id: 94028, name: 'Abyssal Infusion' },
  { aura_key: 'abyssalInfusion', id: 94039, name: 'Abyssal Infusion' },
  { aura_key: 'abyssalInfusion', id: 94078, name: 'Abyssal Infusion' },
  { aura_key: 'abyssalInfusion', id: 94079, name: 'Abyssal Infusion' },
  { aura_key: 'abyssalInfusion', id: 94090, name: 'Abyssal Infusion' },
  { aura_key: 'abyssalInfusion', id: 94091, name: 'Abyssal Infusion' },

  { aura_key: 'moteOfDarkness', id: 99869, name: 'Mote of Darkness' },
  { aura_key: 'moteOfDarkness', id: 99878, name: 'Mote of Darkness' },
  { aura_key: 'moteOfDarkness', id: 99880, name: 'Mote of Darkness' },
  { aura_key: 'moteOfDarkness', id: 99881, name: 'Mote of Darkness' },
  { aura_key: 'moteOfDarkness', id: 99882, name: 'Mote of Darkness' },
  { aura_key: 'moteOfDarkness', id: 99887, name: 'Mote of Darkness' },
  { aura_key: 'moteOfDarkness', id: 99894, name: 'Mote of Darkness' },
  { aura_key: 'moteOfDarkness', id: 99898, name: 'Mote of Darkness' },

  { aura_key: 'phospholuminescentInfusions', id: 79639, name: 'Phospholuminescent Infusion' },
  { aura_key: 'phospholuminescentInfusions', id: 79653, name: 'Phospholuminescent Infusion' },
  { aura_key: 'phospholuminescentInfusions', id: 79661, name: 'Phospholuminescent Infusion' },
  { aura_key: 'phospholuminescentInfusions', id: 79665, name: 'Phospholuminescent Infusion' },
  { aura_key: 'phospholuminescentInfusions', id: 79669, name: 'Phospholuminescent Infusion' },
  { aura_key: 'phospholuminescentInfusions', id: 79674, name: 'Phospholuminescent Infusion' },
  { aura_key: 'phospholuminescentInfusions', id: 85863, name: 'Phospholuminescent Infusion' },
  { aura_key: 'phospholuminescentInfusions', id: 85885, name: 'Phospholuminescent Infusion' },

  { aura_key: 'luminescentRefractors', id: 67370, name: 'Polyluminescent Undulating Refractor (Green)' },
  { aura_key: 'luminescentRefractors', id: 67372, name: 'Polyluminescent Undulating Refractor (Orange)' },
  { aura_key: 'luminescentRefractors', id: 67375, name: 'Polyluminescent Undulating Refractor (Black)' },
  { aura_key: 'luminescentRefractors', id: 79647, name: 'Polyluminescent Undulating Refractor (Teal)' },
  { aura_key: 'luminescentRefractors', id: 81612, name: 'Polyluminescent Undulating Infusion (Green)' },
  { aura_key: 'luminescentRefractors', id: 81624, name: 'Polyluminescent Undulating Infusion (Black)' },
  { aura_key: 'luminescentRefractors', id: 81641, name: 'Polyluminescent Undulating Infusion (Teal)' },
  { aura_key: 'luminescentRefractors', id: 81653, name: 'Polyluminescent Undulating Infusion (Teal)' },
  { aura_key: 'luminescentRefractors', id: 81655, name: 'Polyluminescent Undulating Infusion (Teal)' },
  { aura_key: 'luminescentRefractors', id: 81678, name: 'Polyluminescent Undulating Infusion (Green)' },
  { aura_key: 'luminescentRefractors', id: 81709, name: 'Polyluminescent Undulating Infusion (Black)' },
  { aura_key: 'luminescentRefractors', id: 81727, name: 'Polyluminescent Undulating Infusion (Green)' },
  { aura_key: 'luminescentRefractors', id: 81777, name: 'Polyluminescent Undulating Infusion (Teal)' },
  { aura_key: 'luminescentRefractors', id: 81809, name: 'Polyluminescent Undulating Infusion (Orange)' },
  { aura_key: 'luminescentRefractors', id: 81810, name: 'Polyluminescent Undulating Infusion (Black)' },
  { aura_key: 'luminescentRefractors', id: 81847, name: 'Polyluminescent Undulating Infusion (Orange)' },
  { aura_key: 'luminescentRefractors', id: 81858, name: 'Polyluminescent Undulating Infusion (Teal)' },
  { aura_key: 'luminescentRefractors', id: 81864, name: 'Polyluminescent Undulating Infusion (Orange)' },
  { aura_key: 'luminescentRefractors', id: 81877, name: 'Polyluminescent Undulating Infusion (Black)' },
  { aura_key: 'luminescentRefractors', id: 81881, name: 'Polyluminescent Undulating Infusion (Orange)' },
  { aura_key: 'luminescentRefractors', id: 81911, name: 'Polyluminescent Undulating Infusion (Orange)' },
  { aura_key: 'luminescentRefractors', id: 81930, name: 'Polyluminescent Undulating Infusion (Orange)' },
  { aura_key: 'luminescentRefractors', id: 81948, name: 'Polyluminescent Undulating Infusion (Green)' },
  { aura_key: 'luminescentRefractors', id: 81959, name: 'Polyluminescent Undulating Infusion (Teal)' },
  { aura_key: 'luminescentRefractors', id: 81988, name: 'Polyluminescent Undulating Infusion (Green)' },
  { aura_key: 'luminescentRefractors', id: 82013, name: 'Polyluminescent Undulating Infusion (Black)' },
  { aura_key: 'luminescentRefractors', id: 82039, name: 'Polyluminescent Undulating Infusion (Black)' },
  { aura_key: 'luminescentRefractors', id: 82055, name: 'Polyluminescent Undulating Infusion (Green)' },
  { aura_key: 'luminescentRefractors', id: 85682, name: 'Polyluminescent Undulating Infusion (Green)' },
  { aura_key: 'luminescentRefractors', id: 85694, name: 'Polyluminescent Undulating Infusion (Orange)' },
  { aura_key: 'luminescentRefractors', id: 85974, name: 'Polyluminescent Undulating Infusion (Black)' },
  { aura_key: 'luminescentRefractors', id: 86068, name: 'Polyluminescent Undulating Infusion (Teal)' },
  { aura_key: 'luminescentRefractors', id: 86183, name: 'Polyluminescent Undulating Infusion (Green)' },
  { aura_key: 'luminescentRefractors', id: 86248, name: 'Polyluminescent Undulating Infusion (Black)' },
  { aura_key: 'luminescentRefractors', id: 86310, name: 'Polyluminescent Undulating Infusion (Orange)' },
  { aura_key: 'luminescentRefractors', id: 86312, name: 'Polyluminescent Undulating Infusion (Teal)' },

  { aura_key: 'polysaturatingInfusions', id: 89005, name: 'Polysaturating Reverberating Infusion (Purple)' },
  { aura_key: 'polysaturatingInfusions', id: 89007, name: 'Polysaturating Reverberating Infusion (Gray)' },
  { aura_key: 'polysaturatingInfusions', id: 89012, name: 'Polysaturating Reverberating Infusion (Gray)' },
  { aura_key: 'polysaturatingInfusions', id: 89013, name: 'Polysaturating Reverberating Infusion (Gray)' },
  { aura_key: 'polysaturatingInfusions', id: 89016, name: 'Polysaturating Reverberating Infusion (Gray)' },
  { aura_key: 'polysaturatingInfusions', id: 89017, name: 'Polysaturating Reverberating Infusion (Purple)' },
  { aura_key: 'polysaturatingInfusions', id: 89020, name: 'Polysaturating Reverberating Infusion (Gray)' },
  { aura_key: 'polysaturatingInfusions', id: 89026, name: 'Polysaturating Reverberating Infusion (Red)' },
  { aura_key: 'polysaturatingInfusions', id: 89028, name: 'Polysaturating Reverberating Infusion (Red)' },
  { aura_key: 'polysaturatingInfusions', id: 89032, name: 'Polysaturating Reverberating Infusion (Red)' },
  { aura_key: 'polysaturatingInfusions', id: 89034, name: 'Polysaturating Reverberating Infusion (Red)' },
  { aura_key: 'polysaturatingInfusions', id: 89037, name: 'Polysaturating Reverberating Infusion (Purple)' },
  { aura_key: 'polysaturatingInfusions', id: 89039, name: 'Polysaturating Reverberating Infusion (Purple)' },
  { aura_key: 'polysaturatingInfusions', id: 89042, name: 'Polysaturating Reverberating Infusion (Purple)' },
  { aura_key: 'polysaturatingInfusions', id: 89049, name: 'Polysaturating Reverberating Infusion (Purple)' },
  { aura_key: 'polysaturatingInfusions', id: 89052, name: 'Polysaturating Reverberating Infusion (Red)' },
  { aura_key: 'polysaturatingInfusions', id: 89054, name: 'Polysaturating Reverberating Infusion (Gray)' },
  { aura_key: 'polysaturatingInfusions', id: 89059, name: 'Polysaturating Reverberating Infusion (Red)' },
  { aura_key: 'polysaturatingInfusions', id: 89063, name: 'Polysaturating Reverberating Infusion (Purple)' },
  { aura_key: 'polysaturatingInfusions', id: 89070, name: 'Polysaturating Reverberating Infusion (Purple)' },
  { aura_key: 'polysaturatingInfusions', id: 89071, name: 'Polysaturating Reverberating Infusion (Red)' },
  { aura_key: 'polysaturatingInfusions', id: 89074, name: 'Polysaturating Reverberating Infusion (Gray)' },
  { aura_key: 'polysaturatingInfusions', id: 89075, name: 'Polysaturating Reverberating Infusion (Red)' },
  { aura_key: 'polysaturatingInfusions', id: 89078, name: 'Polysaturating Reverberating Infusion (Gray)' },

  { aura_key: 'emberInfusions', id: 89010, name: 'Ember Infusion' },
  { aura_key: 'emberInfusions', id: 89015, name: 'Ember Infusion' },
  { aura_key: 'emberInfusions', id: 89021, name: 'Ember Infusion' },
  { aura_key: 'emberInfusions', id: 89038, name: 'Ember Infusion' },
  { aura_key: 'emberInfusions', id: 89040, name: 'Ember Infusion' },
  { aura_key: 'emberInfusions', id: 89046, name: 'Ember Infusion' },
  { aura_key: 'emberInfusions', id: 89060, name: 'Ember Infusion' },
  { aura_key: 'emberInfusions', id: 89065, name: 'Ember Infusion' },

  { aura_key: 'mysticInfusions', id: 90966, name: 'Mystic Infusion' },
  { aura_key: 'mysticInfusions', id: 90977, name: 'Mystic Infusion' },
  { aura_key: 'mysticInfusions', id: 90982, name: 'Mystic Infusion' },
  { aura_key: 'mysticInfusions', id: 91050, name: 'Mystic Infusion' },
  { aura_key: 'mysticInfusions', id: 91054, name: 'Mystic Infusion' },
  { aura_key: 'mysticInfusions', id: 91086, name: 'Mystic Infusion' },
  { aura_key: 'mysticInfusions', id: 91099, name: 'Mystic Infusion' },
  { aura_key: 'mysticInfusions', id: 91111, name: 'Mystic Infusion' },

  { aura_key: 'ghostlyInfusions', id: 77274, name: 'Ghostly Infusion' },
  { aura_key: 'ghostlyInfusions', id: 77303, name: 'Ghostly Infusion' },
  { aura_key: 'ghostlyInfusions', id: 77310, name: 'Ghostly Infusion' },
  { aura_key: 'ghostlyInfusions', id: 77316, name: 'Ghostly Infusion' },
  { aura_key: 'ghostlyInfusions', id: 77366, name: 'Ghostly Infusion' },
  { aura_key: 'ghostlyInfusions', id: 77394, name: 'Ghostly Infusion' },
  { aura_key: 'ghostlyInfusions', id: 85644, name: 'Ghostly Infusion' },
  { aura_key: 'ghostlyInfusions', id: 85945, name: 'Ghostly Infusion' },

  { aura_key: 'peerlessInfusions', id: 91140, name: 'Peerless Infusion' },
  { aura_key: 'peerlessInfusions', id: 91152, name: 'Peerless Infusion' },
  { aura_key: 'peerlessInfusions', id: 91154, name: 'Peerless Infusion' },
  { aura_key: 'peerlessInfusions', id: 91180, name: 'Peerless Infusion' },
  { aura_key: 'peerlessInfusions', id: 91202, name: 'Peerless Infusion' },
  { aura_key: 'peerlessInfusions', id: 91210, name: 'Peerless Infusion' },
  { aura_key: 'peerlessInfusions', id: 91221, name: 'Peerless Infusion' },
  { aura_key: 'peerlessInfusions', id: 91236, name: 'Peerless Infusion' },

  { aura_key: 'baubleInfusions', id: 78012, name: 'Moto\'s Unstable Bauble Infusion: Blue' },
  { aura_key: 'baubleInfusions', id: 78016, name: 'Moto\'s Unstable Bauble Infusion: Red' },
  { aura_key: 'baubleInfusions', id: 78028, name: 'Moto\'s Unstable Bauble Infusion: Red' },
  { aura_key: 'baubleInfusions', id: 78030, name: 'Moto\'s Unstable Bauble Infusion: Red' },
  { aura_key: 'baubleInfusions', id: 78031, name: 'Moto\'s Unstable Bauble Infusion: Red' },
  { aura_key: 'baubleInfusions', id: 78052, name: 'Moto\'s Unstable Bauble Infusion: Blue' },
  { aura_key: 'baubleInfusions', id: 78054, name: 'Moto\'s Unstable Bauble Infusion: Blue' },
  { aura_key: 'baubleInfusions', id: 78057, name: 'Moto\'s Unstable Bauble Infusion: Red' },
  { aura_key: 'baubleInfusions', id: 78079, name: 'Moto\'s Unstable Bauble Infusion: Blue' },
  { aura_key: 'baubleInfusions', id: 78086, name: 'Moto\'s Unstable Bauble Infusion: Blue' },
  { aura_key: 'baubleInfusions', id: 78090, name: 'Moto\'s Unstable Bauble Infusion: Blue' },
  { aura_key: 'baubleInfusions', id: 78097, name: 'Moto\'s Unstable Bauble Infusion: Red' },
  { aura_key: 'baubleInfusions', id: 86446, name: 'Moto\'s Unstable Bauble Infusion: Red' },
  { aura_key: 'baubleInfusions', id: 86453, name: 'Moto\'s Unstable Bauble Infusion: Red' },
  { aura_key: 'baubleInfusions', id: 86552, name: 'Moto\'s Unstable Bauble Infusion: Blue' },
  { aura_key: 'baubleInfusions', id: 86571, name: 'Moto\'s Unstable Bauble Infusion: Blue' },

  { aura_key: 'wintersHeartInfusions', id: 79943, name: 'Winter\'s Heart Infusion' },
  { aura_key: 'wintersHeartInfusions', id: 79957, name: 'Winter\'s Heart Infusion' },
  { aura_key: 'wintersHeartInfusions', id: 79959, name: 'Winter\'s Heart Infusion' },
  { aura_key: 'wintersHeartInfusions', id: 79978, name: 'Winter\'s Heart Infusion' },
  { aura_key: 'wintersHeartInfusions', id: 79994, name: 'Winter\'s Heart Infusion' },
  { aura_key: 'wintersHeartInfusions', id: 80063, name: 'Winter\'s Heart Infusion' },
  { aura_key: 'wintersHeartInfusions', id: 85718, name: 'Winter\'s Heart Infusion' },
  { aura_key: 'wintersHeartInfusions', id: 85734, name: 'Winter\'s Heart Infusion' },

  { aura_key: 'snowDiamondInfusions', id: 86401, name: 'Snow Diamond Infusion' },
  { aura_key: 'snowDiamondInfusions', id: 86405, name: 'Snow Diamond Infusion' },
  { aura_key: 'snowDiamondInfusions', id: 86407, name: 'Snow Diamond Infusion' },
  { aura_key: 'snowDiamondInfusions', id: 86537, name: 'Snow Diamond Infusion' },
  { aura_key: 'snowDiamondInfusions', id: 86597, name: 'Snow Diamond Infusion' },
  { aura_key: 'snowDiamondInfusions', id: 86665, name: 'Snow Diamond Infusion' },
  { aura_key: 'snowDiamondInfusions', id: 86666, name: 'Snow Diamond Infusion' },
  { aura_key: 'snowDiamondInfusions', id: 86704, name: 'Snow Diamond Infusion' },

  { aura_key: 'toyShellInfusions', id: 89382, name: 'Toy-Shell Infusion' },
  { aura_key: 'toyShellInfusions', id: 89391, name: 'Toy-Shell Infusion' },
  { aura_key: 'toyShellInfusions', id: 89401, name: 'Toy-Shell Infusion' },
  { aura_key: 'toyShellInfusions', id: 89411, name: 'Toy-Shell Infusion' },
  { aura_key: 'toyShellInfusions', id: 89413, name: 'Toy-Shell Infusion' },
  { aura_key: 'toyShellInfusions', id: 89415, name: 'Toy-Shell Infusion' },
  { aura_key: 'toyShellInfusions', id: 89426, name: 'Toy-Shell Infusion' },
  { aura_key: 'toyShellInfusions', id: 89427, name: 'Toy-Shell Infusion' },

  { aura_key: 'imperialEverbloom', id: 98083, name: 'Imperial Everbloom' },
  { aura_key: 'imperialEverbloom', id: 98088, name: 'Imperial Everbloom' },
  { aura_key: 'imperialEverbloom', id: 98105, name: 'Imperial Everbloom' },
  { aura_key: 'imperialEverbloom', id: 98119, name: 'Imperial Everbloom' },
  { aura_key: 'imperialEverbloom', id: 98131, name: 'Imperial Everbloom' },
  { aura_key: 'imperialEverbloom', id: 98145, name: 'Imperial Everbloom' },
  { aura_key: 'imperialEverbloom', id: 98153, name: 'Imperial Everbloom' },
  { aura_key: 'imperialEverbloom', id: 98163, name: 'Imperial Everbloom' },

  { aura_key: 'clockworkInfusion', id: 99195, name: 'Clockwork Infusion' },
  { aura_key: 'clockworkInfusion', id: 99206, name: 'Clockwork Infusion' },
  { aura_key: 'clockworkInfusion', id: 99209, name: 'Clockwork Infusion' },
  { aura_key: 'clockworkInfusion', id: 99213, name: 'Clockwork Infusion' },
  { aura_key: 'clockworkInfusion', id: 99237, name: 'Clockwork Infusion' },
  { aura_key: 'clockworkInfusion', id: 99240, name: 'Clockwork Infusion' },
  { aura_key: 'clockworkInfusion', id: 99244, name: 'Clockwork Infusion' },
  { aura_key: 'clockworkInfusion', id: 99248, name: 'Clockwork Infusion' },

  { aura_key: 'jotunInfusion', id: 101124, name: 'Jotun Infusion' },
  { aura_key: 'jotunInfusion', id: 101146, name: 'Jotun Infusion' },
  { aura_key: 'jotunInfusion', id: 101169, name: 'Jotun Infusion' },
  { aura_key: 'jotunInfusion', id: 101171, name: 'Jotun Infusion' },
  { aura_key: 'jotunInfusion', id: 101226, name: 'Jotun Infusion' },
  { aura_key: 'jotunInfusion', id: 101259, name: 'Jotun Infusion' },
  { aura_key: 'jotunInfusion', id: 101262, name: 'Jotun Infusion' },
  { aura_key: 'jotunInfusion', id: 101276, name: 'Jotun Infusion' },

  { aura_key: 'possessionInfusion', id: 100008, name: 'Possession Infusion' },
  { aura_key: 'possessionInfusion', id: 100065, name: 'Possession Infusion' },
  { aura_key: 'possessionInfusion', id: 100302, name: 'Possession Infusion' },
  { aura_key: 'possessionInfusion', id: 100407, name: 'Possession Infusion' },
  { aura_key: 'possessionInfusion', id: 100513, name: 'Possession Infusion' },
  { aura_key: 'possessionInfusion', id: 100806, name: 'Possession Infusion' },
  { aura_key: 'possessionInfusion', id: 100913, name: 'Possession Infusion' },
  { aura_key: 'possessionInfusion', id: 100914, name: 'Possession Infusion' },

  { aura_key: 'silentSymphony', id: 99914, name: 'Silent Symphony' },
  { aura_key: 'silentSymphony', id: 99921, name: 'Silent Symphony' },
  { aura_key: 'silentSymphony', id: 99929, name: 'Silent Symphony' },
  { aura_key: 'silentSymphony', id: 99932, name: 'Silent Symphony' },
  { aura_key: 'silentSymphony', id: 99939, name: 'Silent Symphony' },
  { aura_key: 'silentSymphony', id: 99940, name: 'Silent Symphony' },
  { aura_key: 'silentSymphony', id: 99946, name: 'Silent Symphony' },
  { aura_key: 'silentSymphony', id: 99948, name: 'Silent Symphony' },

  { aura_key: 'arcaneFlowInfusion', id: 101199, name: 'Arcane Flow Infusion' },
  { aura_key: 'arcaneFlowInfusion', id: 101223, name: 'Arcane Flow Infusion' },
  { aura_key: 'arcaneFlowInfusion', id: 101234, name: 'Arcane Flow Infusion' },
  { aura_key: 'arcaneFlowInfusion', id: 101237, name: 'Arcane Flow Infusion' },
  { aura_key: 'arcaneFlowInfusion', id: 101261, name: 'Arcane Flow Infusion' },
  { aura_key: 'arcaneFlowInfusion', id: 101263, name: 'Arcane Flow Infusion' },
  { aura_key: 'arcaneFlowInfusion', id: 101278, name: 'Arcane Flow Infusion' },
  { aura_key: 'arcaneFlowInfusion', id: 101279, name: 'Arcane Flow Infusion' },

  { aura_key: 'mistwalkerInfusion', id: 99784, name: 'Mistwalker Infusion' },
  { aura_key: 'mistwalkerInfusion', id: 99789, name: 'Mistwalker Infusion' },
  { aura_key: 'mistwalkerInfusion', id: 99790, name: 'Mistwalker Infusion' },
  { aura_key: 'mistwalkerInfusion', id: 99809, name: 'Mistwalker Infusion' },
  { aura_key: 'mistwalkerInfusion', id: 99824, name: 'Mistwalker Infusion' },
  { aura_key: 'mistwalkerInfusion', id: 99839, name: 'Mistwalker Infusion' },
  { aura_key: 'mistwalkerInfusion', id: 99848, name: 'Mistwalker Infusion' },
  { aura_key: 'mistwalkerInfusion', id: 99850, name: 'Mistwalker Infusion' },
  // -- GENERATE-END --
]

export default GAME_DATA_ITEMS_CATEGORIES_COSMETIC_AURAS
