export interface GameDataSkinsCategoriesAureneLegendaryVariants {
  /** The grouping key for the skins */
  variant_key: string

  /** The item id */
  id: number

  /** The item name */
  name: string
}

// prettier-ignore
const GAME_DATA_SKINS_CATEGORIES_AURENE_LEGENDARY_VARIANTS: Array<GameDataSkinsCategoriesAureneLegendaryVariants> = [
  // -- GENERATE-START --
  { variant_key: 'variantSkins', id: 10730, name: 'Zhaitan\'s Rending Skin' },
  { variant_key: 'variantSkins', id: 10284, name: 'Zhaitan\'s Tail Skin' },
  { variant_key: 'variantSkins', id: 10517, name: 'Zhaitan\'s Persuasion Skin' },
  { variant_key: 'variantSkins', id: 10739, name: 'Zhaitan\'s Bite Skin' },
  { variant_key: 'variantSkins', id: 10497, name: 'Zhaitan\'s Claw Skin' },
  { variant_key: 'variantSkins', id: 10738, name: 'Zhaitan\'s Scale Skin' },
  { variant_key: 'variantSkins', id: 10729, name: 'Zhaitan\'s Argument Skin' },
  { variant_key: 'variantSkins', id: 10678, name: 'Zhaitan\'s Insight Skin' },
  { variant_key: 'variantSkins', id: 10515, name: 'Zhaitan\'s Weight Skin' },
  { variant_key: 'variantSkins', id: 10260, name: 'Zhaitan\'s Flight Skin' },
  { variant_key: 'variantSkins', id: 10422, name: 'Zhaitan\'s Gaze Skin' },
  { variant_key: 'variantSkins', id: 10266, name: 'Zhaitan\'s Breath Skin' },
  { variant_key: 'variantSkins', id: 10350, name: 'Zhaitan\'s Fang Skin' },
  { variant_key: 'variantSkins', id: 10410, name: 'Zhaitan\'s Voice Skin' },
  { variant_key: 'variantSkins', id: 10593, name: 'Zhaitan\'s Wisdom Skin' },
  { variant_key: 'variantSkins', id: 10601, name: 'Zhaitan\'s Wing Skin' },
  { variant_key: 'variantSkins', id: 10436, name: 'Mordremoth\'s Tail Skin' },
  { variant_key: 'variantSkins', id: 10320, name: 'Mordremoth\'s Insight Skin' },
  { variant_key: 'variantSkins', id: 10552, name: 'Mordremoth\'s Flight Skin' },
  { variant_key: 'variantSkins', id: 10347, name: 'Mordremoth\'s Bite Skin' },
  { variant_key: 'variantSkins', id: 10481, name: 'Mordremoth\'s Gaze Skin' },
  { variant_key: 'variantSkins', id: 10499, name: 'Mordremoth\'s Rending Skin' },
  { variant_key: 'variantSkins', id: 10353, name: 'Mordremoth\'s Argument Skin' },
  { variant_key: 'variantSkins', id: 10539, name: 'Mordremoth\'s Claw Skin' },
  { variant_key: 'variantSkins', id: 10630, name: 'Mordremoth\'s Wing Skin' },
  { variant_key: 'variantSkins', id: 10415, name: 'Mordremoth\'s Voice Skin' },
  { variant_key: 'variantSkins', id: 10472, name: 'Mordremoth\'s Persuasion Skin' },
  { variant_key: 'variantSkins', id: 10381, name: 'Mordremoth\'s Wisdom Skin' },
  { variant_key: 'variantSkins', id: 10537, name: 'Mordremoth\'s Scale Skin' },
  { variant_key: 'variantSkins', id: 10358, name: 'Mordremoth\'s Fang Skin' },
  { variant_key: 'variantSkins', id: 10541, name: 'Mordremoth\'s Breath Skin' },
  { variant_key: 'variantSkins', id: 10711, name: 'Mordremoth\'s Weight Skin' },
  { variant_key: 'variantSkins', id: 10583, name: 'Kralkatorrik\'s Wing Skin' },
  { variant_key: 'variantSkins', id: 10712, name: 'Kralkatorrik\'s Bite Skin' },
  { variant_key: 'variantSkins', id: 10394, name: 'Kralkatorrik\'s Argument Skin' },
  { variant_key: 'variantSkins', id: 10632, name: 'Kralkatorrik\'s Scale Skin' },
  { variant_key: 'variantSkins', id: 10429, name: 'Kralkatorrik\'s Gaze Skin' },
  { variant_key: 'variantSkins', id: 10628, name: 'Kralkatorrik\'s Claw Skin' },
  { variant_key: 'variantSkins', id: 10685, name: 'Kralkatorrik\'s Wisdom Skin' },
  { variant_key: 'variantSkins', id: 10414, name: 'Kralkatorrik\'s Insight Skin' },
  { variant_key: 'variantSkins', id: 10453, name: 'Kralkatorrik\'s Fang Skin' },
  { variant_key: 'variantSkins', id: 10693, name: 'Kralkatorrik\'s Weight Skin' },
  { variant_key: 'variantSkins', id: 10355, name: 'Kralkatorrik\'s Voice Skin' },
  { variant_key: 'variantSkins', id: 10437, name: 'Kralkatorrik\'s Persuasion Skin' },
  { variant_key: 'variantSkins', id: 10676, name: 'Kralkatorrik\'s Rending Skin' },
  { variant_key: 'variantSkins', id: 10251, name: 'Kralkatorrik\'s Breath Skin' },
  { variant_key: 'variantSkins', id: 10329, name: 'Kralkatorrik\'s Tail Skin' },
  { variant_key: 'variantSkins', id: 10748, name: 'Kralkatorrik\'s Flight Skin' },
  { variant_key: 'variantSkins', id: 10294, name: 'Jormag\'s Weight Skin' },
  { variant_key: 'variantSkins', id: 10525, name: 'Jormag\'s Bite Skin' },
  { variant_key: 'variantSkins', id: 10553, name: 'Jormag\'s Fang Skin' },
  { variant_key: 'variantSkins', id: 10747, name: 'Jormag\'s Wing Skin' },
  { variant_key: 'variantSkins', id: 10449, name: 'Jormag\'s Gaze Skin' },
  { variant_key: 'variantSkins', id: 10327, name: 'Jormag\'s Insight Skin' },
  { variant_key: 'variantSkins', id: 10417, name: 'Jormag\'s Tail Skin' },
  { variant_key: 'variantSkins', id: 10363, name: 'Jormag\'s Claw Skin' },
  { variant_key: 'variantSkins', id: 10480, name: 'Jormag\'s Argument Skin' },
  { variant_key: 'variantSkins', id: 10343, name: 'Jormag\'s Persuasion Skin' },
  { variant_key: 'variantSkins', id: 10697, name: 'Jormag\'s Breath Skin' },
  { variant_key: 'variantSkins', id: 10544, name: 'Jormag\'s Voice Skin' },
  { variant_key: 'variantSkins', id: 10250, name: 'Jormag\'s Flight Skin' },
  { variant_key: 'variantSkins', id: 10390, name: 'Jormag\'s Rending Skin' },
  { variant_key: 'variantSkins', id: 10332, name: 'Jormag\'s Scale Skin' },
  { variant_key: 'variantSkins', id: 10301, name: 'Jormag\'s Wisdom Skin' },
  { variant_key: 'variantSkins', id: 10491, name: 'Primordus\'s Flight Skin' },
  { variant_key: 'variantSkins', id: 10579, name: 'Primordus\'s Scale Skin' },
  { variant_key: 'variantSkins', id: 10311, name: 'Primordus\'s Breath Skin' },
  { variant_key: 'variantSkins', id: 10696, name: 'Primordus\'s Rending Skin' },
  { variant_key: 'variantSkins', id: 10287, name: 'Primordus\'s Wing Skin' },
  { variant_key: 'variantSkins', id: 10674, name: 'Primordus\'s Wisdom Skin' },
  { variant_key: 'variantSkins', id: 10346, name: 'Primordus\'s Claw Skin' },
  { variant_key: 'variantSkins', id: 10388, name: 'Primordus\'s Persuasion Skin' },
  { variant_key: 'variantSkins', id: 10660, name: 'Primordus\'s Fang Skin' },
  { variant_key: 'variantSkins', id: 10366, name: 'Primordus\'s Gaze Skin' },
  { variant_key: 'variantSkins', id: 10513, name: 'Primordus\'s Argument Skin' },
  { variant_key: 'variantSkins', id: 10645, name: 'Primordus\'s Tail Skin' },
  { variant_key: 'variantSkins', id: 10288, name: 'Primordus\'s Voice Skin' },
  { variant_key: 'variantSkins', id: 10252, name: 'Primordus\'s Insight Skin' },
  { variant_key: 'variantSkins', id: 10345, name: 'Primordus\'s Bite Skin' },
  { variant_key: 'variantSkins', id: 10532, name: 'Primordus\'s Weight Skin' },
  { variant_key: 'variantSkins', id: 10259, name: 'Soo-Won\'s Gaze Skin' },
  { variant_key: 'variantSkins', id: 10623, name: 'Soo-Won\'s Rending Skin' },
  { variant_key: 'variantSkins', id: 10720, name: 'Soo-Won\'s Breath Skin' },
  { variant_key: 'variantSkins', id: 10244, name: 'Soo-Won\'s Voice Skin' },
  { variant_key: 'variantSkins', id: 10448, name: 'Soo-Won\'s Argument Skin' },
  { variant_key: 'variantSkins', id: 10521, name: 'Soo-Won\'s Insight Skin' },
  { variant_key: 'variantSkins', id: 10570, name: 'Soo-Won\'s Persuasion Skin' },
  { variant_key: 'variantSkins', id: 10324, name: 'Soo-Won\'s Scale Skin' },
  { variant_key: 'variantSkins', id: 10309, name: 'Soo-Won\'s Bite Skin' },
  { variant_key: 'variantSkins', id: 10716, name: 'Soo-Won\'s Weight Skin' },
  { variant_key: 'variantSkins', id: 10596, name: 'Soo-Won\'s Fang Skin' },
  { variant_key: 'variantSkins', id: 10511, name: 'Soo-Won\'s Wing Skin' },
  { variant_key: 'variantSkins', id: 10490, name: 'Soo-Won\'s Wisdom Skin' },
  { variant_key: 'variantSkins', id: 10550, name: 'Soo-Won\'s Claw Skin' },
  { variant_key: 'variantSkins', id: 10564, name: 'Soo-Won\'s Flight Skin' },
  { variant_key: 'variantSkins', id: 10496, name: 'Soo-Won\'s Tail Skin' },
  // -- GENERATE-END --
]

export default GAME_DATA_SKINS_CATEGORIES_AURENE_LEGENDARY_VARIANTS
